# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  test:
    docker:
      - image: kennethreitz/bake:ci
    resource_class: xlarge
    parallelism: 3

    working_directory: /app

    steps:
      - checkout
      - run:
          name: $ pipenv install…
          command: |
            export PIPENV_MAX_SUBPROCESS=128
            pipenv install --dev --system --deploy
      - run:
          name: BATS tests [sharded]
          command: |
            cd tests
            mkdir -p /app/reports/bats
            bats $(circleci tests glob '*.bats' | circleci tests split) > "/app/reports/bats/$CIRCLE_NODE_INDEX.tap"
            # bats *.bats > "/app/reports/bats/$CIRCLE_NODE_INDEX.tap"

      - store_test_results:
          path: reports
  docker:
    docker:
      - image: kennethreitz/bake:ci
    resource_class: xlarge
    parallelism: 3

    working_directory: /app

    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: $ docker login
          command:
            docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_PASSWORD}
            docker login docker.pkg.github.com -u ${GITHUB_USERNAME} -p ${GITHUB_TOKEN}

      - run:
          name: $ bake docker/push
          command: bake docker/push

workflows:
  version: 2
  test:
    jobs:
      - test
  docker:
    jobs:
      - test
      - docker:
          requires:
            - test
          filters:
            branches:
              only:
                - master
            tags:
              only: /^v.*/
