# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: docker.pkg.github.com/kennethreitz/bake/bake:ci
        auth:
          username: kennethreitz # can specify string literal values
          password: $GITHUB_TOKEN
    resource_class: 2xlarge+
    parallelism: 6

    working_directory: /app

    steps:
      - checkout
      # - setup_remote_docker:
      #     docker_layer_caching: true
      - run:
          name: $ pipenv install…
          command: |
            export PIPENV_MAX_SUBPROCESS=128
            pipenv install --dev --system --deploy
      - run:
          name: BATS tests [sharded]
          command: |
            cd tests
            mkdir -p reports/bats
            bats $(circleci tests glob '*.bats' | circleci tests split) > "reports/bats/$CIRCLE_NODE_INDEX.tap"

      - store_test_results:
          path: reports
